export const SAMPLE_DATA = [
  {
    firstName: "Michal",
    lastName: "Nieruchalski",
    age: 30,
    address: { city: "Poznan", street: "Polwiejska" },
  },
  {
    firstName: "Sophie",
    lastName: "Dubois",
    age: 27,
    address: { city: "Paris", street: "Rue de Rivoli" },
  },
  {
    firstName: "Luca",
    lastName: "Rossi",
    age: 34,
    address: { city: "Milan", street: "Via Montenapoleone" },
  },
  {
    firstName: "Yuki",
    lastName: "Tanaka",
    age: 29,
    address: { city: "Tokyo", street: "Takeshita" },
  },
  {
    firstName: "Carlos",
    lastName: "Garcia",
    age: 41,
    address: { city: "Barcelona", street: "Las Ramblas" },
  },
  {
    firstName: "Amara",
    lastName: "Diallo",
    age: 33,
    address: { city: "Dakar", street: "Avenue Cheikh Anta Diop" },
  },
  {
    firstName: "Emily",
    lastName: "Johnson",
    age: 26,
    address: { city: "New York", street: "Broadway" },
  },
  {
    firstName: "Lars",
    lastName: "Eriksson",
    age: 45,
    address: { city: "Stockholm", street: "Drottninggatan" },
  },
  {
    firstName: "Fatima",
    lastName: "Al-Rashid",
    age: 38,
    address: { city: "Dubai", street: "Sheikh Zayed Road" },
  },
  {
    firstName: "Chen",
    lastName: "Wei",
    age: 31,
    address: { city: "Shanghai", street: "Nanjing Road" },
  },
  {
    firstName: "Priya",
    lastName: "Sharma",
    age: 24,
    address: { city: "Mumbai", street: "Marine Drive" },
  },
  {
    firstName: "James",
    lastName: "Okafor",
    age: 37,
    address: { city: "Lagos", street: "Victoria Island Blvd" },
  },
  {
    firstName: "Elena",
    lastName: "Petrov",
    age: 29,
    address: { city: "Moscow", street: "Arbat" },
  },
  {
    firstName: "Rafael",
    lastName: "Santos",
    age: 43,
    address: { city: "São Paulo", street: "Avenida Paulista" },
  },
  {
    firstName: "Mei",
    lastName: "Lin",
    age: 22,
    address: { city: "Taipei", street: "Zhongxiao East Road" },
  },
  {
    firstName: "Oliver",
    lastName: "Smith",
    age: 36,
    address: { city: "London", street: "Oxford Street" },
  },
];
